import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { DesignSystemConfig, ColorValue } from "./types.js";
import { loadConfig, findConfigPath, getProjectRoot } from "./config.js";

function stringifyColorValue(value: ColorValue, indent: number): string {
  if (typeof value === "string") {
    return `"${value}"`;
  }

  const spaces = "  ".repeat(indent);
  const lines: string[] = ["{"];
  for (const [key, val] of Object.entries(value)) {
    lines.push(`${spaces}  ${key}: ${stringifyColorValue(val, indent + 1)},`);
  }
  lines.push(`${spaces}}`);
  return lines.join("\n");
}

function generateTS(config: DesignSystemConfig): string {
  const lines: string[] = [];
  lines.push("// generated by driftguard — do not edit");

  // Colors
  lines.push("export const colors = {");
  for (const [name, value] of Object.entries(config.tokens.colors)) {
    const valueStr = stringifyColorValue(value, 1);
    lines.push(`  ${name}: ${valueStr},`);
  }
  lines.push("} as const;");

  lines.push("");

  // Spacing
  const spacingValues = config.tokens.spacingScale.join(", ");
  lines.push(`export const spacing = [${spacingValues}] as const;`);
  lines.push("");

  return lines.join("\n");
}

function flattenColors(
  colors: Record<string, ColorValue>,
  prefix = "",
): Record<string, string> {
  const result: Record<string, string> = {};

  for (const [key, value] of Object.entries(colors)) {
    const path = prefix ? `${prefix}-${key}` : key;
    if (typeof value === "string") {
      result[path] = value;
    } else {
      Object.assign(result, flattenColors(value, path));
    }
  }

  return result;
}

function generateCSS(config: DesignSystemConfig): string {
  const lines: string[] = [];
  lines.push("/* generated by driftguard — do not edit */");
  lines.push(":root {");

  // Color custom properties (flattened)
  const flatColors = flattenColors(config.tokens.colors);
  for (const [path, value] of Object.entries(flatColors)) {
    lines.push(`  --color-${path}: ${value};`);
  }

  // Spacing custom properties
  for (const value of config.tokens.spacingScale) {
    lines.push(`  --spacing-${value}: ${value}px;`);
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

export async function runGenerate(): Promise<void> {
  const config = await loadConfig();
  const configPath = findConfigPath()!;
  const projectRoot = getProjectRoot(configPath);

  if (!config.generate) {
    console.log(
      'No "generate" field in driftguard.config.ts.\n\n' +
        "Add a generate config to specify output paths:\n\n" +
        '  generate: {\n' +
        '    ts: "src/tokens.ts",\n' +
        '    css: "src/tokens.css",\n' +
        "  },\n",
    );
    return;
  }

  if (config.generate.ts) {
    const outPath = resolve(projectRoot, config.generate.ts);
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, generateTS(config));
    console.log(`  \u2713 ${config.generate.ts}`);
  }

  if (config.generate.css) {
    const outPath = resolve(projectRoot, config.generate.css);
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, generateCSS(config));
    console.log(`  \u2713 ${config.generate.css}`);
  }
}
