import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { DesignSystemConfig } from "./types.js";
import { loadConfig, findConfigPath, getProjectRoot } from "./config.js";

function generateTS(config: DesignSystemConfig): string {
  const lines: string[] = [];
  lines.push("// generated by driftguard — do not edit");

  // Colors
  lines.push("export const colors = {");
  for (const [name, hex] of Object.entries(config.tokens.colors)) {
    lines.push(`  ${name}: "${hex}",`);
  }
  lines.push("} as const;");

  lines.push("");

  // Spacing
  const spacingValues = config.tokens.spacingScale.join(", ");
  lines.push(`export const spacing = [${spacingValues}] as const;`);
  lines.push("");

  return lines.join("\n");
}

function generateCSS(config: DesignSystemConfig): string {
  const lines: string[] = [];
  lines.push("/* generated by driftguard — do not edit */");
  lines.push(":root {");

  // Color custom properties
  for (const [name, hex] of Object.entries(config.tokens.colors)) {
    lines.push(`  --color-${name}: ${hex};`);
  }

  // Spacing custom properties
  for (const value of config.tokens.spacingScale) {
    lines.push(`  --spacing-${value}: ${value}px;`);
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

export function runGenerate(): void {
  const config = loadConfig();
  const configPath = findConfigPath()!;
  const projectRoot = getProjectRoot(configPath);

  if (!config.generate) {
    console.log(
      'No "generate" field in driftguard.config.json.\n\n' +
        "Add a generate config to specify output paths:\n\n" +
        '  "generate": {\n' +
        '    "ts": "src/tokens.ts",\n' +
        '    "css": "src/tokens.css"\n' +
        "  }\n",
    );
    return;
  }

  if (config.generate.ts) {
    const outPath = resolve(projectRoot, config.generate.ts);
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, generateTS(config));
    console.log(`  \u2713 ${config.generate.ts}`);
  }

  if (config.generate.css) {
    const outPath = resolve(projectRoot, config.generate.css);
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, generateCSS(config));
    console.log(`  \u2713 ${config.generate.css}`);
  }
}
